
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- CSS only -->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" 
integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
<link rel="stylesheet" href="log.css">
    <title>log</title>
</head>
<body>
    <div class="row row-cols-md-1">
        <nav class="navbar bg-primary">
            <div class="col container-fluid">
                <div class="container-fluid">
                <h2 > <i class="fa-solid fa-house" style="color:black; padding-right:10px; font-size:30px;"></i>Institut Supérieur des Etudes Technologiques <span id="bizerte">Bizerte</span></h2>
                </div>
            </div>
            <div class="col">
                <h2 id="h2-col2">College<i class="fa-solid fa-screwdriver-wrench"></i></h2>
            </div>
    </div>

    <div class="row">
        <div class="col">
        <form class="form" method="post" action="index.php">
                             <!-- --------------------title --------------------------->

            <div class="mb-3 container-fluid">
                
                <button type="button" class="btn btn-info" style="float:right;margin-bottom:20px;" id="btn_inscrit" ><a href="../signup">S'inscrire</a></button>
            </div>
                            <!-- --------------------utilisateur --------------------------->
            <div class="mb-3">
                <label  class="form-label">Nom Utilisateur</label>
                <input type="text" class="form-control" name="utilisateur" required>
                <div  class="form-text">Nous ne partagerons jamais votre e-mail avec quelqu'un d'autre .</div>
            </div>
                            <!-- --------------------password --------------------------->
            <div class="mb-3">
                <label for="exampleInputPassword1" class="form-label" required>Mot de passe</label>
                <input type="password" class="form-control" name="password">

                <div id="emailHelp" class="form-text">Mot de passe oublié ? <a href="" style="text-decoration:none;">Cliquez ici</a></div>
            </div>
                            <!-- --------------------check--------------------------->
            <div class="mb-3 form-check">
                <input type="checkbox" class="form-check-input" id="exampleCheck1">
                <label class="form-check-label" for="exampleCheck1">Enregistrer</label>
            </div>
                            <!-- --------------------button --------------------------->
            <button type="submit" class="btn btn-primary" name="send">Login</button>
        </form>
        </div>
    </div>
    
    
    <script src="https://kit.fontawesome.com/c5bebe1cfa.js" crossorigin="anonymous"></script>
</body>
</html>